#!/usr/bin/env ruby

require 'pathname'
require 'find'


def needs_cleanup? path
  path.to_s !~ %r{^./_build} && [ '.ml', '.mli', '.sail', '.template.v', '.template.html' ].include?(path.extname)
end


def cleanup path
  contents = path.read
  updated_contents = contents.gsub(%r{ +\n}, "\n")  
  path.write updated_contents

  contents != updated_contents
end


dirty = false

Find.find('.') do |path|
  path = Pathname.new path

  if needs_cleanup? path
    dirty = cleanup(path) || dirty  # Be careful with order
  end
end

exit (dirty ? 1 : 0)
