(*

   Module for pretty printing.

   
   Originally we relied on PPrint, but we wanted the possibility to add annotations,
   which we rely on the indicate which parts of the output were generated by which
   parts of the code.

*)


include Functor
