(*

   Module for pretty printing.

   
   Originally we relied on PPrint, but we wanted the possibility to add annotations,
   which we rely on the indicate which parts of the output were generated by which
   parts of the code. Afterwards we also added support for decorations.

*)


module Make(Annotation : Functor.ANNOTATION) = struct
  module DocImpl = Functor.Make(Annotation)
  include DocImpl
  include HelperFunctions.Make(DocImpl)
end
